//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSC.Services.Simuladores.Contracts
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimuladorPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.InformacionInicialPeticion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionCreditoPeticion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionDPFPeticion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalPeticion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialPeticion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.TestPeticion))]
    public partial class SimuladorPeticion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string PasswordField;

        private string UsuarioField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InformacionInicialPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class InformacionInicialPeticion : BMSC.Services.Simuladores.Contracts.SimuladorPeticion
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionCreditoPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionCreditoPeticion : BMSC.Services.Simuladores.Contracts.SimuladorPeticion
    {

        private string CesantiaField;

        private int IdPlazoTipoCreditoField;

        private decimal MontoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cesantia
        {
            get
            {
                return this.CesantiaField;
            }
            set
            {
                this.CesantiaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlazoTipoCredito
        {
            get
            {
                return this.IdPlazoTipoCreditoField;
            }
            set
            {
                this.IdPlazoTipoCreditoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionDPFPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionDPFPeticion : BMSC.Services.Simuladores.Contracts.SimuladorPeticion
    {

        private int MonedaField;

        private decimal MontoField;

        private int PlazoEnDiasField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlazoEnDias
        {
            get
            {
                return this.PlazoEnDiasField;
            }
            set
            {
                this.PlazoEnDiasField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionDPFIncrementalPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionDPFIncrementalPeticion : BMSC.Services.Simuladores.Contracts.SimuladorPeticion
    {

        private int MonedaField;

        private decimal MontoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionCreditoViviendaSocialPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionCreditoViviendaSocialPeticion : BMSC.Services.Simuladores.Contracts.SimuladorPeticion
    {

        private string CesantiaField;

        private int IdPlazoTipoCreditoField;

        private decimal MontoField;

        private decimal ValorComercialField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cesantia
        {
            get
            {
                return this.CesantiaField;
            }
            set
            {
                this.CesantiaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlazoTipoCredito
        {
            get
            {
                return this.IdPlazoTipoCreditoField;
            }
            set
            {
                this.IdPlazoTipoCreditoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorComercial
        {
            get
            {
                return this.ValorComercialField;
            }
            set
            {
                this.ValorComercialField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TestPeticion", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class TestPeticion : BMSC.Services.Simuladores.Contracts.SimuladorPeticion
    {

        private string TestField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Test
        {
            get
            {
                return this.TestField;
            }
            set
            {
                this.TestField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimuladorRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionCreditoRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionDPFRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMSC.Services.Simuladores.Contracts.InformacionInicialRespuesta))]
    public partial class SimuladorRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime FechaOperacionField;

        private string MensajeResultadoField;

        private int ResultadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaOperacion
        {
            get
            {
                return this.FechaOperacionField;
            }
            set
            {
                this.FechaOperacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeResultado
        {
            get
            {
                return this.MensajeResultadoField;
            }
            set
            {
                this.MensajeResultadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionCreditoRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionCreditoRespuesta : BMSC.Services.Simuladores.Contracts.SimuladorRespuesta
    {

        private decimal CuotaMaximaField;

        private BMSC.Services.Simuladores.Contracts.CuotaInfo[] CuotasField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaMaxima
        {
            get
            {
                return this.CuotaMaximaField;
            }
            set
            {
                this.CuotaMaximaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public BMSC.Services.Simuladores.Contracts.CuotaInfo[] Cuotas
        {
            get
            {
                return this.CuotasField;
            }
            set
            {
                this.CuotasField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionDPFRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionDPFRespuesta : BMSC.Services.Simuladores.Contracts.SimuladorRespuesta
    {

        private decimal InteresField;

        private decimal IvaField;

        private decimal MontoInteresConNitField;

        private decimal MontoInteresSinNitField;

        private decimal MontoRetencionIvaField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interes
        {
            get
            {
                return this.InteresField;
            }
            set
            {
                this.InteresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Iva
        {
            get
            {
                return this.IvaField;
            }
            set
            {
                this.IvaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoInteresConNit
        {
            get
            {
                return this.MontoInteresConNitField;
            }
            set
            {
                this.MontoInteresConNitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoInteresSinNit
        {
            get
            {
                return this.MontoInteresSinNitField;
            }
            set
            {
                this.MontoInteresSinNitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoRetencionIva
        {
            get
            {
                return this.MontoRetencionIvaField;
            }
            set
            {
                this.MontoRetencionIvaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionDPFIncrementalRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionDPFIncrementalRespuesta : BMSC.Services.Simuladores.Contracts.SimuladorRespuesta
    {

        private BMSC.Services.Simuladores.Contracts.EmisionDPFIncrementalInfo[] EmisionesField;

        private decimal TotalInteresGanadoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public BMSC.Services.Simuladores.Contracts.EmisionDPFIncrementalInfo[] Emisiones
        {
            get
            {
                return this.EmisionesField;
            }
            set
            {
                this.EmisionesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalInteresGanado
        {
            get
            {
                return this.TotalInteresGanadoField;
            }
            set
            {
                this.TotalInteresGanadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SimulacionCreditoViviendaSocialRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class SimulacionCreditoViviendaSocialRespuesta : BMSC.Services.Simuladores.Contracts.SimuladorRespuesta
    {

        private decimal CuotaMaximaField;

        private BMSC.Services.Simuladores.Contracts.CuotaInfo[] CuotasField;

        private decimal TasaField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaMaxima
        {
            get
            {
                return this.CuotaMaximaField;
            }
            set
            {
                this.CuotaMaximaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public BMSC.Services.Simuladores.Contracts.CuotaInfo[] Cuotas
        {
            get
            {
                return this.CuotasField;
            }
            set
            {
                this.CuotasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tasa
        {
            get
            {
                return this.TasaField;
            }
            set
            {
                this.TasaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InformacionInicialRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class InformacionInicialRespuesta : BMSC.Services.Simuladores.Contracts.SimuladorRespuesta
    {

        private int[] ListaPlazosDPFField;

        private BMSC.Services.Simuladores.Contracts.TipoCreditoInfo[] ListaTiposCreditoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ListaPlazosDPF
        {
            get
            {
                return this.ListaPlazosDPFField;
            }
            set
            {
                this.ListaPlazosDPFField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public BMSC.Services.Simuladores.Contracts.TipoCreditoInfo[] ListaTiposCredito
        {
            get
            {
                return this.ListaTiposCreditoField;
            }
            set
            {
                this.ListaTiposCreditoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoCreditoInfo", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class TipoCreditoInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdTipoCreditoField;

        private string NombreField;

        private BMSC.Services.Simuladores.Contracts.PlazoTipoCreditoInfo[] PlazosDisponiblesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCredito
        {
            get
            {
                return this.IdTipoCreditoField;
            }
            set
            {
                this.IdTipoCreditoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public BMSC.Services.Simuladores.Contracts.PlazoTipoCreditoInfo[] PlazosDisponibles
        {
            get
            {
                return this.PlazosDisponiblesField;
            }
            set
            {
                this.PlazosDisponiblesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CuotaInfo", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class CuotaInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private decimal AmortizacionCapitalField;

        private decimal CuotaTotalField;

        private System.DateTime FechaField;

        private decimal InteresesField;

        private int NumeroCuotaField;

        private decimal SaldoCapitalField;

        private decimal SeguroCesantiaField;

        private decimal SeguroDesgravamenField;

        private decimal ValorCuotaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmortizacionCapital
        {
            get
            {
                return this.AmortizacionCapitalField;
            }
            set
            {
                this.AmortizacionCapitalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaTotal
        {
            get
            {
                return this.CuotaTotalField;
            }
            set
            {
                this.CuotaTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Intereses
        {
            get
            {
                return this.InteresesField;
            }
            set
            {
                this.InteresesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuota
        {
            get
            {
                return this.NumeroCuotaField;
            }
            set
            {
                this.NumeroCuotaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoCapital
        {
            get
            {
                return this.SaldoCapitalField;
            }
            set
            {
                this.SaldoCapitalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SeguroCesantia
        {
            get
            {
                return this.SeguroCesantiaField;
            }
            set
            {
                this.SeguroCesantiaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SeguroDesgravamen
        {
            get
            {
                return this.SeguroDesgravamenField;
            }
            set
            {
                this.SeguroDesgravamenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota
        {
            get
            {
                return this.ValorCuotaField;
            }
            set
            {
                this.ValorCuotaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EmisionDPFIncrementalInfo", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class EmisionDPFIncrementalInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private decimal InteresGanadoField;

        private string NombreEmisionField;

        private int NumeroEmisionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InteresGanado
        {
            get
            {
                return this.InteresGanadoField;
            }
            set
            {
                this.InteresGanadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmision
        {
            get
            {
                return this.NombreEmisionField;
            }
            set
            {
                this.NombreEmisionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEmision
        {
            get
            {
                return this.NumeroEmisionField;
            }
            set
            {
                this.NumeroEmisionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlazoTipoCreditoInfo", Namespace = "http://schemas.datacontract.org/2004/07/BMSC.Services.Simuladores.Contracts")]
    public partial class PlazoTipoCreditoInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string[] CesantiasField;

        private int IdPlazoTipoCreditoField;

        private int PlazoEnMesesField;

        private decimal SpreadFijoField;

        private decimal TREField;

        private decimal TasaFijaField;

        private int TasaVariableAPartirDelMesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Cesantias
        {
            get
            {
                return this.CesantiasField;
            }
            set
            {
                this.CesantiasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlazoTipoCredito
        {
            get
            {
                return this.IdPlazoTipoCreditoField;
            }
            set
            {
                this.IdPlazoTipoCreditoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlazoEnMeses
        {
            get
            {
                return this.PlazoEnMesesField;
            }
            set
            {
                this.PlazoEnMesesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpreadFijo
        {
            get
            {
                return this.SpreadFijoField;
            }
            set
            {
                this.SpreadFijoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TRE
        {
            get
            {
                return this.TREField;
            }
            set
            {
                this.TREField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TasaFija
        {
            get
            {
                return this.TasaFijaField;
            }
            set
            {
                this.TasaFijaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TasaVariableAPartirDelMes
        {
            get
            {
                return this.TasaVariableAPartirDelMesField;
            }
            set
            {
                this.TasaVariableAPartirDelMesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ISimuladoresService")]
public interface ISimuladoresService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/Test", ReplyAction = "http://tempuri.org/ISimuladoresService/TestResponse")]
    string Test(BMSC.Services.Simuladores.Contracts.TestPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/Test", ReplyAction = "http://tempuri.org/ISimuladoresService/TestResponse")]
    System.Threading.Tasks.Task<string> TestAsync(BMSC.Services.Simuladores.Contracts.TestPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/ObtenerInformacionInicial", ReplyAction = "http://tempuri.org/ISimuladoresService/ObtenerInformacionInicialResponse")]
    BMSC.Services.Simuladores.Contracts.InformacionInicialRespuesta ObtenerInformacionInicial(BMSC.Services.Simuladores.Contracts.InformacionInicialPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/ObtenerInformacionInicial", ReplyAction = "http://tempuri.org/ISimuladoresService/ObtenerInformacionInicialResponse")]
    System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.InformacionInicialRespuesta> ObtenerInformacionInicialAsync(BMSC.Services.Simuladores.Contracts.InformacionInicialPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularCredito", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularCreditoResponse")]
    BMSC.Services.Simuladores.Contracts.SimulacionCreditoRespuesta SimularCredito(BMSC.Services.Simuladores.Contracts.SimulacionCreditoPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularCredito", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularCreditoResponse")]
    System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionCreditoRespuesta> SimularCreditoAsync(BMSC.Services.Simuladores.Contracts.SimulacionCreditoPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularDPF", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularDPFResponse")]
    BMSC.Services.Simuladores.Contracts.SimulacionDPFRespuesta SimularDPF(BMSC.Services.Simuladores.Contracts.SimulacionDPFPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularDPF", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularDPFResponse")]
    System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionDPFRespuesta> SimularDPFAsync(BMSC.Services.Simuladores.Contracts.SimulacionDPFPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularDPFIncremental", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularDPFIncrementalResponse")]
    BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalRespuesta SimularDPFIncremental(BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularDPFIncremental", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularDPFIncrementalResponse")]
    System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalRespuesta> SimularDPFIncrementalAsync(BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularCreditoViviendaSocial", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularCreditoViviendaSocialResponse")]
    BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialRespuesta SimularCreditoViviendaSocial(BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialPeticion peticion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISimuladoresService/SimularCreditoViviendaSocial", ReplyAction = "http://tempuri.org/ISimuladoresService/SimularCreditoViviendaSocialResponse")]
    System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialRespuesta> SimularCreditoViviendaSocialAsync(BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialPeticion peticion);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISimuladoresServiceChannel : ISimuladoresService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SimuladoresServiceClient : System.ServiceModel.ClientBase<ISimuladoresService>, ISimuladoresService
{

    public SimuladoresServiceClient()
    {
    }

    public SimuladoresServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public SimuladoresServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SimuladoresServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SimuladoresServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string Test(BMSC.Services.Simuladores.Contracts.TestPeticion peticion)
    {
        return base.Channel.Test(peticion);
    }

    public System.Threading.Tasks.Task<string> TestAsync(BMSC.Services.Simuladores.Contracts.TestPeticion peticion)
    {
        return base.Channel.TestAsync(peticion);
    }

    public BMSC.Services.Simuladores.Contracts.InformacionInicialRespuesta ObtenerInformacionInicial(BMSC.Services.Simuladores.Contracts.InformacionInicialPeticion peticion)
    {
        return base.Channel.ObtenerInformacionInicial(peticion);
    }

    public System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.InformacionInicialRespuesta> ObtenerInformacionInicialAsync(BMSC.Services.Simuladores.Contracts.InformacionInicialPeticion peticion)
    {
        return base.Channel.ObtenerInformacionInicialAsync(peticion);
    }

    public BMSC.Services.Simuladores.Contracts.SimulacionCreditoRespuesta SimularCredito(BMSC.Services.Simuladores.Contracts.SimulacionCreditoPeticion peticion)
    {
        return base.Channel.SimularCredito(peticion);
    }

    public System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionCreditoRespuesta> SimularCreditoAsync(BMSC.Services.Simuladores.Contracts.SimulacionCreditoPeticion peticion)
    {
        return base.Channel.SimularCreditoAsync(peticion);
    }

    public BMSC.Services.Simuladores.Contracts.SimulacionDPFRespuesta SimularDPF(BMSC.Services.Simuladores.Contracts.SimulacionDPFPeticion peticion)
    {
        return base.Channel.SimularDPF(peticion);
    }

    public System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionDPFRespuesta> SimularDPFAsync(BMSC.Services.Simuladores.Contracts.SimulacionDPFPeticion peticion)
    {
        return base.Channel.SimularDPFAsync(peticion);
    }

    public BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalRespuesta SimularDPFIncremental(BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalPeticion peticion)
    {
        return base.Channel.SimularDPFIncremental(peticion);
    }

    public System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalRespuesta> SimularDPFIncrementalAsync(BMSC.Services.Simuladores.Contracts.SimulacionDPFIncrementalPeticion peticion)
    {
        return base.Channel.SimularDPFIncrementalAsync(peticion);
    }

    public BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialRespuesta SimularCreditoViviendaSocial(BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialPeticion peticion)
    {
        return base.Channel.SimularCreditoViviendaSocial(peticion);
    }

    public System.Threading.Tasks.Task<BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialRespuesta> SimularCreditoViviendaSocialAsync(BMSC.Services.Simuladores.Contracts.SimulacionCreditoViviendaSocialPeticion peticion)
    {
        return base.Channel.SimularCreditoViviendaSocialAsync(peticion);
    }
}
